-- Táblák létrehozása Festivia adattár
-- events/users/locations/categories/registrations/event_configurations


-- Events
CREATE TABLE festivia.events (
	id INT PRIMARY KEY GENERATED BY DEFAULT as identity,
	title VARCHAR(256) NOT NULL,
	description TEXT NOT NULL,
	location_id INT,
    start_date TIMESTAMPTZ,
	end_date TIMESTAMPTZ,
	category_id INT,
	price NUMERIC NOT NULL DEFAULT 0 CHECK ( price >= 0 ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    duration_minutes INT GENERATED ALWAYS AS ( EXTRACT(EPOCH FROM end_date - start_date)/60 ) STORED
    CONSTRAINT start_date_best_end_date CHECK ( start_date < end_date )
);

-- users
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(256) NOT NULL UNIQUE,
    first_name VARCHAR(256),
    last_name VARCHAR(256),
    email VARCHAR(256) NOT NULL UNIQUE,
    full_name VARCHAR(513) GENERATED ALWAYS AS ( first_name || ' ' || last_name ) STORED
);


-- locations
CREATE TABLE locations
(
    id SERIAL PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    country VARCHAR(100) NOT NULL
);

-- categories
CREATE TABLE categories
(
    id       SERIAL PRIMARY KEY,
    category VARCHAR(256) NOT NULL UNIQUE
);

-- registrations
create table registrations(
	user_id INT,
	event_id INT,
	PRIMARY KEY (user_id, event_id),
	created_at TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT fk_events FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL  
);

-- event_configurations
CREATE TABLE event_configurations(
    event_id          INT PRIMARY KEY,
    deadline          TIMESTAMPTZ,
    max_registrations INT
);